export const tasks = [
  {
    id: 1,
    website: "楽天市場",
    product: "[楽天市場] 富士フィルム フィルム",
    account: "123456",
    credit: "1",
    quantity: "1",
    progress: "70",
    date: "2024/07/09",
    timer: "13:00:23",
  },
  {
    id: 2,
    website: "",
    product: "",
    account: "",
    credit: "0",
    quantity: "1",
    progress: "0",
    timer: "",
  },
  {
    id: 3,
    website: "",
    product: "",
    account: "",
    credit: "0",
    quantity: "1",
    progress: "0",
    timer: "",
  },
  {
    id: 4,
    website: "",
    product: "",
    account: "",
    credit: "0",
    quantity: "1",
    progress: "0",
    timer: "",
  },
  {
    id: 5,
    website: "",
    product: "",
    account: "",
    credit: "0",
    quantity: "1",
    progress: "0",
    timer: "",
  },
  {
    id: 6,
    website: "",
    product: "",
    account: "",
    credit: "0",
    quantity: "1",
    progress: "0",
    timer: "",
  },
  {
    id: 7,
    website: "",
    product: "",
    account: "",
    credit: "0",
    quantity: "1",
    progress: "0",
    timer: "",
  },
  {
    id: 8,
    website: "",
    product: "",
    account: "",
    credit: "0",
    quantity: "1",
    progress: "0",
    timer: "",
  },
  {
    id: 9,
    website: "",
    product: "",
    account: "",
    credit: "0",
    quantity: "1",
    progress: "0",
    timer: "",
  },
  {
    id: 10,
    website: "",
    product: "",
    account: "",
    credit: "0",
    quantity: "1",
    progress: "0",
    timer: "",
  },
  {
    id: 11,
    website: "",
    product: "",
    account: "",
    credit: "0",
    quantity: "1",
    progress: "0",
    timer: "",
  },
  {
    id: 12,
    website: "",
    product: "",
    account: "",
    credit: "0",
    quantity: "1",
    progress: "0",
    timer: "",
  },
  {
    id: 13,
    website: "",
    product: "",
    account: "",
    credit: "0",
    quantity: "1",
    progress: "0",
    timer: "",
  },
  {
    id: 14,
    website: "",
    product: "",
    account: "",
    credit: "0",
    quantity: "1",
    progress: "0",
    timer: "",
  },
  {
    id: 15,
    website: "",
    product: "",
    account: "",
    credit: "0",
    quantity: "1",
    progress: "0",
    timer: "",
  },
  {
    id: 16,
    website: "",
    product: "",
    account: "",
    credit: "0",
    quantity: "1",
    progress: "0",
    timer: "",
  },
  {
    id: 17,
    website: "",
    product: "",
    account: "",
    credit: "0",
    quantity: "1",
    progress: "0",
    timer: "",
  },
  {
    id: 18,
    website: "",
    product: "",
    account: "",
    credit: "0",
    quantity: "1",
    progress: "0",
    timer: "",
  },
  {
    id: 19,
    website: "",
    product: "",
    account: "",
    credit: "0",
    quantity: "1",
    progress: "0",
    timer: "",
  },
  {
    id: 20,
    website: "",
    product: "",
    account: "",
    credit: "0",
    quantity: "1",
    progress: "0",
    timer: "",
  },

  // Add more rows as necessary
];
